name: Build RedPill DSM loader (support 7.1 Critical Update pat)

on: 
  workflow_dispatch:
    inputs:
      dsmodel:
        description: 'Input Full DSM model [DS3622xs+|RS4021xs+|DVA3221|DS918+|DS920+|DS3615xs]'
        required: true
        default: 'DS3622xs+'
      major:
        description: 'Input DSM Major version'
        required: true
        default: '7.1.0'
      os_version:
        description: 'Input DSM Build Number'
        required: true
        default: '42661'
      minor:
        description: 'Input Minor Revision (0 is no minor)'
        required: true
        default: '0'
      system:
        description: 'Input VM or real'
        required: true
        default: 'VM'
jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build dsm 7.1
        id: build-dsm-71
        run: |
            bash build-universal-update-7.1.sh ${{github.event.inputs.dsmodel}} ${{github.event.inputs.major}} ${{github.event.inputs.os_version}} ${{github.event.inputs.minor}} ${{github.event.inputs.system}}
      - name: Archive loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-${{github.event.inputs.dsmodel}}_${{github.event.inputs.major}}-loader
          path: output/
